# Generated by Django 4.0 on 2022-09-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('title', models.CharField(default='', max_length=100)),
                ('released', models.DateField()),
                ('episode', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
