# Generated by Django 4.1.1 on 2022-09-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='rating',
            field=models.FloatField(blank=True),
        ),
    ]
