# Generated by Django 4.1.1 on 2022-09-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_alter_episode_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
